services:
  - type: web
    name: inventory-cashier-web
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: inventory-cashier-db
          property: connectionString

databases:
  - name: inventory-cashier-db
    plan: free
    databaseName: inventory_cashier
    user: inventory_cashier
    postgresMajorVersion: "15"
